INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("1", "Cherry Blossom Estate", "Ap #553-3731 Sit Rd");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("2", "Horseshoe Grang", "972-7058 Pellentesque Rd.");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("3", "Two Pines Estate", "P.O. Box 146, 9149 Hymenaeos. Ave");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("4", "Moonshadow Farms", "Ap #196-5848 Quisque Rd.");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("5", "Mossy Oak Vineyard", "Ap #341-4012 Proin Road");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("6", "Meadowgrove Gardens", "P.O. Box 109, 1752 Tempus Street");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("7", "White Oak Acres", "821 Dolor Ave");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("8", "Bittersweet Lands", "Ap #153-1787 Mollis. Ave");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("9", "Windy Oaks Fields", "764-1552 In, Road");
INSERT INTO `ifarm`.farm (_id, name, address)  VALUES ("10", "Rattlesnake Ranch", "P.O. Box 279, 8717 Id Road");